# Basic Python

## 1. Split this string

In [ ]:
s = "Hi there Sam!"

In [1]:
s="Hi there Sam!"
s.split()

['Hi', 'there', 'Sam!']

## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [ ]:
planet = "Earth"
diameter = 12742

In [2]:
planet = "Earth"
diameter = 12742
print("The diameter of {} is {}".format("Earth",12742))

The diameter of Earth is 12742


## 3. In this nest dictionary grab the word "hello"

In [ ]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [3]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

# Numpy

In [ ]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [4]:
import numpy as np
arr=np.zeros(10,dtype=int)
print(arr)

[0 0 0 0 0 0 0 0 0 0]


In [5]:
import numpy as np
arr=np.ones(10,dtype=int)*5
print(arr)

[5 5 5 5 5 5 5 5 5 5]


## 5. Create an array of all the even integers from 20 to 35

In [6]:
l=[x for x in range(20,36)]

is_even=lambda y:y%2==0 
l2=list(filter(is_even,l))
print(l2)

[20, 22, 24, 26, 28, 30, 32, 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [7]:
import numpy as np
arr=np.array([0,1,2,3,4,5,6,7,8])
newarr=arr.reshape(3,3)
print(newarr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [9]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
newarr=np.concatenate((a,b),axis=0)
print(newarr)

[1 2 3 4 5 6]


# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [ ]:
import pandas as pd


In [10]:
import pandas as pd 
record = {"name":["Sneha","Shree","Swetha"],"Place":["Chennai","Pune","Bangalore"]}
df=pd.DataFrame(record)
print(df)

     name      Place
0   Sneha    Chennai
1   Shree       Pune
2  Swetha  Bangalore


## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [11]:
import pandas as pd
df=pd.date_range(start='1/1/2023',end='10/2/2023')
print(df)

DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
               '2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08',
               '2023-01-09', '2023-01-10',
               ...
               '2023-09-23', '2023-09-24', '2023-09-25', '2023-09-26',
               '2023-09-27', '2023-09-28', '2023-09-29', '2023-09-30',
               '2023-10-01', '2023-10-02'],
              dtype='datetime64[ns]', length=275, freq='D')


## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [ ]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [12]:
import pandas as pd 
lst= [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]
df=pd.DataFrame(lst,columns=['column1','column2','column3'])
print(df)


   column1 column2  column3
0        1     aaa       22
1        2     bbb       25
2        3     ccc       24
